In [1]:
import numpy as np

In [2]:
np.sqrt(0.25 * (1. - 0.25) / 10000)

0.004330127018922193

In [5]:
np.random.multinomial(1000, [0.25, 0.3, 0.1, 0.35])

array([246, 300, 103, 351])

In [6]:
res = np.array([246, 300, 103, 351])

In [8]:
p = res / 1000.
np.sqrt(p * (1. - p) / 1000.)

array([0.01361925, 0.01449138, 0.00961202, 0.01509301])

In [9]:
p

array([0.246, 0.3  , 0.103, 0.351])

In [13]:
import json
d = json.loads(r'''{"changed": false, "module_stderr": "Shared connection to iutweb01.iut.icepp.s.u-tokyo.ac.jp closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1648624596.394823-146122-38761280563485/AnsiballZ_x509_certificate_info.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1648624596.394823-146122-38761280563485/AnsiballZ_x509_certificate_info.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1648624596.394823-146122-38761280563485/AnsiballZ_x509_certificate_info.py\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible_collections.community.crypto.plugins.modules.x509_certificate_info', init_globals=dict(_module_fqn='ansible_collections.community.crypto.plugins.modules.x509_certificate_info', _modlib_path=modlib_path),\r\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\r\n    _run_code(code, mod_globals, init_globals,\r\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_community.crypto.x509_certificate_info_payload_tuw4sgaj/ansible_community.crypto.x509_certificate_info_payload.zip/ansible_collections/community/crypto/plugins/modules/x509_certificate_info.py\", line 452, in <module>\r\n  File \"/tmp/ansible_community.crypto.x509_certificate_info_payload_tuw4sgaj/ansible_community.crypto.x509_certificate_info_payload.zip/ansible_collections/community/crypto/plugins/modules/x509_certificate_info.py\", line 436, in main\r\n  File \"/tmp/ansible_community.crypto.x509_certificate_info_payload_tuw4sgaj/ansible_community.crypto.x509_certificate_info_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate_info.py\", line 228, in get_info\r\n  File \"/tmp/ansible_community.crypto.x509_certificate_info_payload_tuw4sgaj/ansible_community.crypto.x509_certificate_info_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/module_backends/certificate_info.py\", line 381, in _get_all_extensions\r\n  File \"/tmp/ansible_community.crypto.x509_certificate_info_payload_tuw4sgaj/ansible_community.crypto.x509_certificate_info_payload.zip/ansible_collections/community/crypto/plugins/module_utils/crypto/cryptography_support.py\", line 71, in cryptography_get_extensions_from_cert\r\nAttributeError: 'builtins.Certificate' object has no attribute '_backend'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}''')


In [16]:
d.keys()

dict_keys(['changed', 'module_stderr', 'module_stdout', 'msg', 'rc'])

In [17]:
print(d['module_stdout'])

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1648624596.394823-146122-38761280563485/AnsiballZ_x509_certificate_info.py", line 100, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1648624596.394823-146122-38761280563485/AnsiballZ_x509_certificate_info.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1648624596.394823-146122-38761280563485/AnsiballZ_x509_certificate_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.crypto.plugins.modules.x509_certificate_info', init_globals=dict(_module_fqn='ansible_collections.community.crypto.plugins.modules.x509_certificate_info', _modlib_path=modlib_path),
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, 

In [19]:
from qiskit import IBMQ

IBMQ.load_account()
provider = IBMQ.get_provider(hub='ibm-q', group='open', project='main')

backend = provider.get_backend('ibmq_armonk')

In [20]:
dir(backend.configuration())

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_channel_qubit_map',
 '_control_channels',
 '_data',
 '_get_channel_prefix_index',
 '_parse_channels',
 '_qubit_channel_map',
 'acquire',
 'acquisition_latency',
 'backend_name',
 'backend_version',
 'basis_gates',
 'channels',
 'conditional',
 'conditional_latency',
 'control',
 'control_channels',
 'coupling_map',
 'credits_required',
 'describe',
 'description',
 'discriminators',
 'drive',
 'dt',
 'dtm',
 'dynamic_reprate_enabled',
 'from_dict',
 'gates',
 'get_channel_qubits',
 'get_qubit_channels',
 'hamiltonian',
 'local',
 'max_experiments',
 'max_shots',
 'meas_kernels',
 'meas_l